# Generated by Django 5.1.3 on 2024-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wm_sign", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="id",
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="hash",
            field=models.CharField(
                default="--", max_length=1000, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
